name: lofit
description: "Food and recipe tracking app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  flutter_bloc: ^9.1.0
  provider: ^6.1.2
  dio: ^5.8.0+1
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  equatable: ^2.0.7
  font_awesome_flutter: ^10.8.0
  barcode_scan2: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true
